### PR TITLE
Fix the redirectURL casing in the HAR response

### PR DESCRIPTION
**Pull request by 0xced**
According to the standard it must be `redirectURL` and not `redirectUrl`.

### CODE REVIEW

**Comment by jeanplevesque** [comment]
@0xced Can you link that standard for reference?

**Comment by 0xced** [comment]
Sure, here is the [HTTP Archive](https://w3c.github.io/web-performance/specs/HAR/Overview.html) specification document. Even though it was never published by the W3C Web Performance Working Group and has been abandoned many tools have implemented it.

For example, in JetBrains IDEs, opening a har file produces a warning when `redirectUrl` is used.
Screenshot 2023-04-17 at 18 18 06

The warning disappears as soon as the proper `redirectURL` key is used.
Screenshot 2023-04-17 at 18 18 32

**Comment by jeanplevesque** [comment]
@0xced I see! Can you put that information directly in the code so that someone else doesn't do the opposite change later on? No need for screenshots obviously, but perhaps some explanation in the `<remarks>` tags below the `<summary>`? You can put the link and even explain the IDE example.

**Comment by 0xced** [comment]
Sure, done in c7741575403afc8147dd46f6a141e10efb3c87d9.

**Review by francoisalbert — APPROVED** [review]

**Comment by 0xced** [comment]
Any chance to merge this (and maybe also #11) then release a new version on NuGet?

**Pull request merged**
